package core;

public enum TimeflecksEvent
{
	EVERYTHING_NEEDS_REFRESH,
	GENERAL_REFRESH,
	DAY_WEEK_VIEW_SWITCHED,
	DATE_LEFT_ONE_BUTTON,
	DATE_RIGHT_ONE_BUTTON,
	DATE_TODAY_BUTTON,
	DATE_LEFT_SEVEN_BUTTON,
	DATE_RIGHT_SEVEN_BUTTON
}
