package core;

/**
 * An event that occurs within the Timeflecks application.
 * 
 */
public enum TimeflecksEvent
{
	EVERYTHING_NEEDS_REFRESH,
	GENERAL_REFRESH,
	DAY_WEEK_VIEW_SWITCHED,
	DATE_LEFT_ONE_BUTTON,
	DATE_RIGHT_ONE_BUTTON,
	DATE_TODAY_BUTTON,
	DATE_LEFT_SEVEN_BUTTON,
	DATE_RIGHT_SEVEN_BUTTON,
	CHANGED_POSSIBLE_TAGS,
	INVALIDATED_FILTERED_TASK_LIST,
	CREATED_EDIT_PANEL,
	DISMISSED_EDIT_PANEL
}
